apiVersion : apps/v1
kind: Deployment
metadata:
  name: akashgame 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akashgame
  template:
    metadata:
      labels:
        app: akashgame 
    spec:
      containers:
        - name: akashgame 
          image: mylabacr89.azurecr.io/akashgame
          ports:
          - containerPort: 80